sudo: required
language: go

go:
  - "1.10"

services:
 - docker

cache:
  directories:
    - downloads

go_import_path: "github.com/ibm-messaging/mq-container"

before_install:
  - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
  - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
  - sudo apt-get update
  - sudo apt-get -y install docker-ce
  - curl https://glide.sh/get | sh
  - sudo curl -Lo /usr/local/bin/dep https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64
  - sudo chmod +x /usr/local/bin/dep

install:
  - echo nothing

script:
 - make deps
 - make vet
 - make build-devserver
 - make test-devserver

after_success:
 - go get golang.org/x/lint/golint
 - make lint
